#!/usr/bin/expect

set timeout 2
spawn nc -v 127.0.0.1 6667

send -- "NICK pizapaco\r"

send -- "USER 1 2 3 :4\r"

expect ": 001 :Welcome to the Internet Relay Network pizapaco!\r"
send -- "JOIN #elpacochannel\r"

send -- "MODE #elpacochannel +k pepe\r"

send -- "MODE #elpacochannel -k\r"

send -- "MODE #elpacochannel -k\r"

#send -- "MODE #elpacochannel +l 10\r"

#send -- "MODE #elpacochannel +k pepe\r"

#send -- "MODE #elpacochannel +p\r"

#send -- "MODE #elpacochannel +s\r"

#send -- "MODE #elpacochannel -s\r"

#send -- "MODE #elpacochannel -s\r"

interact


## ERRORES

## Eliminar un modo que no está seteado
## Añadir un modo dos o más veces
## Añadir muchos + o -
